//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV.CT.Service.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Calibration_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Calibration_Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NV.CT.Service.Common.Resources.Calibration_Lang", typeof(Calibration_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Calibration Items 的本地化字符串。
        /// </summary>
        public static string Calibration_CalibrationItems {
            get {
                return ResourceManager.GetString("Calibration_CalibrationItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceled running the calibration scenario 的本地化字符串。
        /// </summary>
        public static string Calibration_CancelRunningTheCalibrationScenario {
            get {
                return ResourceManager.GetString("Calibration_CancelRunningTheCalibrationScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , due to prepare ScanParam failed, param Protocols[{0}] = {1} 的本地化字符串。
        /// </summary>
        public static string Calibration_Comma_FailedToPrepareScanParam {
            get {
                return ResourceManager.GetString("Calibration_Comma_FailedToPrepareScanParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure go to the next step? 的本地化字符串。
        /// </summary>
        public static string Calibration_Confirm_GotoNextStep {
            get {
                return ResourceManager.GetString("Calibration_Confirm_GotoNextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to redo? 的本地化字符串。
        /// </summary>
        public static string Calibration_Confirm_Redo {
            get {
                return ResourceManager.GetString("Calibration_Confirm_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame: {0} / {1} 的本地化字符串。
        /// </summary>
        public static string Calibration_Frame_Progress {
            get {
                return ResourceManager.GetString("Calibration_Frame_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History 的本地化字符串。
        /// </summary>
        public static string Calibration_History {
            get {
                return ResourceManager.GetString("Calibration_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string Calibration_Next {
            get {
                return ResourceManager.GetString("Calibration_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protocol 的本地化字符串。
        /// </summary>
        public static string Calibration_Protocol {
            get {
                return ResourceManager.GetString("Calibration_Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raw 的本地化字符串。
        /// </summary>
        public static string Calibration_Raw {
            get {
                return ResourceManager.GetString("Calibration_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        public static string Calibration_Redo {
            get {
                return ResourceManager.GetString("Calibration_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan progress: {0}/{1} 的本地化字符串。
        /// </summary>
        public static string Calibration_Scan_Progress_Doing_Formatter {
            get {
                return ResourceManager.GetString("Calibration_Scan_Progress_Doing_Formatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan progress: {0}/{1}，Done 的本地化字符串。
        /// </summary>
        public static string Calibration_Scan_Progress_Done_Formatter {
            get {
                return ResourceManager.GetString("Calibration_Scan_Progress_Done_Formatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanning Attention 的本地化字符串。
        /// </summary>
        public static string Calibration_Scanning_Attention {
            get {
                return ResourceManager.GetString("Calibration_Scanning_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.No occlusion in the X-ray coverage;
        ///2.No one in the scanning room;
        ///3.Closed the scanning room. 的本地化字符串。
        /// </summary>
        public static string Calibration_Scanning_Attention_Content {
            get {
                return ResourceManager.GetString("Calibration_Scanning_Attention_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scenario 的本地化字符串。
        /// </summary>
        public static string Calibration_Scenario {
            get {
                return ResourceManager.GetString("Calibration_Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection 的本地化字符串。
        /// </summary>
        public static string Calibration_Selection {
            get {
                return ResourceManager.GetString("Calibration_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start running the calibration scenario &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        public static string Calibration_StartRunningScenario {
            get {
                return ResourceManager.GetString("Calibration_StartRunningScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start running the calibration project &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        public static string Calibration_StartRunningTheCalibrationProject {
            get {
                return ResourceManager.GetString("Calibration_StartRunningTheCalibrationProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The calibration task is in progress, please do not leave. 
        ///If you&apos;re sure you want to leave, stop the task before you leave. 的本地化字符串。
        /// </summary>
        public static string Calibration_TipOnExiting {
            get {
                return ResourceManager.GetString("Calibration_TipOnExiting", resourceCulture);
            }
        }
    }
}
