//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV.CT.Service.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common_Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NV.CT.Service.Common.Resources.Common_Lang", typeof(Common_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Common_Export {
            get {
                return ResourceManager.GetString("Common_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go 的本地化字符串。
        /// </summary>
        public static string Common_Go {
            get {
                return ResourceManager.GetString("Common_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History Record 的本地化字符串。
        /// </summary>
        public static string Common_HistoryRecord {
            get {
                return ResourceManager.GetString("Common_HistoryRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        public static string Common_Information {
            get {
                return ResourceManager.GetString("Common_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number 的本地化字符串。
        /// </summary>
        public static string Common_Number {
            get {
                return ResourceManager.GetString("Common_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress 的本地化字符串。
        /// </summary>
        public static string Common_Progress {
            get {
                return ResourceManager.GetString("Common_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress: 的本地化字符串。
        /// </summary>
        public static string Common_Progress1 {
            get {
                return ResourceManager.GetString("Common_Progress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        public static string Common_Result {
            get {
                return ResourceManager.GetString("Common_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Common_Select {
            get {
                return ResourceManager.GetString("Common_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Common_Start {
            get {
                return ResourceManager.GetString("Common_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Common_Status {
            get {
                return ResourceManager.GetString("Common_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string Common_Stop {
            get {
                return ResourceManager.GetString("Common_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Common_Update {
            get {
                return ResourceManager.GetString("Common_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ECG R Wave Delay (ms) 的本地化字符串。
        /// </summary>
        public static string MapUI_ECGRWaveDelayTime {
            get {
                return ResourceManager.GetString("MapUI_ECGRWaveDelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Air Correction Mode 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_AirCorrectionMode {
            get {
                return ResourceManager.GetString("MapUI_Recon_AirCorrectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bone Aritifact 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_BoneAritifactEnable {
            get {
                return ResourceManager.GetString("MapUI_Recon_BoneAritifactEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bowtie 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_Bowtie {
            get {
                return ResourceManager.GetString("MapUI_Recon_Bowtie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cone Angle Artifact Reduce 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_ConeAngleArtifactReduceEnable {
            get {
                return ResourceManager.GetString("MapUI_Recon_ConeAngleArtifactReduceEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Type 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_FilterType {
            get {
                return ResourceManager.GetString("MapUI_Recon_FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fov (mm) 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_FOV {
            get {
                return ResourceManager.GetString("MapUI_Recon_FOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Increment (mm) 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_ImageIncrement {
            get {
                return ResourceManager.GetString("MapUI_Recon_ImageIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Matrix 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_ImageMatrix {
            get {
                return ResourceManager.GetString("MapUI_Recon_ImageMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interp Type 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_InterpType {
            get {
                return ResourceManager.GetString("MapUI_Recon_InterpType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HD Recon 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_IsHDRecon {
            get {
                return ResourceManager.GetString("MapUI_Recon_IsHDRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Recon 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_IsTargetRecon {
            get {
                return ResourceManager.GetString("MapUI_Recon_IsTargetRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IVR_TV Coef 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_IVRTVCoef {
            get {
                return ResourceManager.GetString("MapUI_Recon_IVRTVCoef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metal Aritifact 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_MetalAritifactEnable {
            get {
                return ResourceManager.GetString("MapUI_Recon_MetalAritifactEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patient Position 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_PatientPosition {
            get {
                return ResourceManager.GetString("MapUI_Recon_PatientPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post Denoise Coef 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_PostDenoiseCoef {
            get {
                return ResourceManager.GetString("MapUI_Recon_PostDenoiseCoef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post Denoise Type 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_PostDenoiseType {
            get {
                return ResourceManager.GetString("MapUI_Recon_PostDenoiseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre Binning 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_PreBinning {
            get {
                return ResourceManager.GetString("MapUI_Recon_PreBinning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre Denoise Coef 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_PreDenoiseCoef {
            get {
                return ResourceManager.GetString("MapUI_Recon_PreDenoiseCoef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre Denoise Type 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_PreDenoiseType {
            get {
                return ResourceManager.GetString("MapUI_Recon_PreDenoiseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recon Body Part 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_ReconBodyPart {
            get {
                return ResourceManager.GetString("MapUI_Recon_ReconBodyPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recon ID 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_ReconID {
            get {
                return ResourceManager.GetString("MapUI_Recon_ReconID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recon Type 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_ReconType {
            get {
                return ResourceManager.GetString("MapUI_Recon_ReconType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ring Aritifact 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_RingAritifactEnable {
            get {
                return ResourceManager.GetString("MapUI_Recon_RingAritifactEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scatter Algorithm 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_ScatterAlgorithm {
            get {
                return ResourceManager.GetString("MapUI_Recon_ScatterAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slice Thickness (mm) 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_SliceThickness {
            get {
                return ResourceManager.GetString("MapUI_Recon_SliceThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smooth Z 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_SmoothZEnable {
            get {
                return ResourceManager.GetString("MapUI_Recon_SmoothZEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two Pass 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_TwoPassEnable {
            get {
                return ResourceManager.GetString("MapUI_Recon_TwoPassEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windmill Artifact Reduce 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_WindmillArtifactReduceEnable {
            get {
                return ResourceManager.GetString("MapUI_Recon_WindmillArtifactReduceEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Center 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_WindowCenter {
            get {
                return ResourceManager.GetString("MapUI_Recon_WindowCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Width 的本地化字符串。
        /// </summary>
        public static string MapUI_Recon_WindowWidth {
            get {
                return ResourceManager.GetString("MapUI_Recon_WindowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow Error XRay Source Count 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_AllowErrorXRaySourceCount {
            get {
                return ResourceManager.GetString("MapUI_Scan_AllowErrorXRaySourceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Delete Number 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_AutoDeleteNum {
            get {
                return ResourceManager.GetString("MapUI_Scan_AutoDeleteNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Scan 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_AutoScan {
            get {
                return ResourceManager.GetString("MapUI_Scan_AutoScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body Category 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_BodyCategory {
            get {
                return ResourceManager.GetString("MapUI_Scan_BodyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body Part 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_BodyPart {
            get {
                return ResourceManager.GetString("MapUI_Scan_BodyPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bowtie 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_Bowtie {
            get {
                return ResourceManager.GetString("MapUI_Scan_Bowtie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collimator Offset 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_CollimatorOffsetEnable {
            get {
                return ResourceManager.GetString("MapUI_Scan_CollimatorOffsetEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collimator Open Mode 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_CollimatorOpenMode {
            get {
                return ResourceManager.GetString("MapUI_Scan_CollimatorOpenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collimator Z 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_CollimatorZ {
            get {
                return ResourceManager.GetString("MapUI_Scan_CollimatorZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CTDIvol 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_CTDIvol {
            get {
                return ResourceManager.GetString("MapUI_Scan_CTDIvol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current (mA) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_Current {
            get {
                return ResourceManager.GetString("MapUI_Scan_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Frames 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_DisplayFrames {
            get {
                return ResourceManager.GetString("MapUI_Scan_DisplayFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effective Frames 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_EffectiveFrames {
            get {
                return ResourceManager.GetString("MapUI_Scan_EffectiveFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exposure Delay (s) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_ExposureDelayTime {
            get {
                return ResourceManager.GetString("MapUI_Scan_ExposureDelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exposure Mode 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_ExposureMode {
            get {
                return ResourceManager.GetString("MapUI_Scan_ExposureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exposure Time (ms) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_ExposureTime {
            get {
                return ResourceManager.GetString("MapUI_Scan_ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exposure Trigger Mode 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_ExposureTriggerMode {
            get {
                return ResourceManager.GetString("MapUI_Scan_ExposureTriggerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focal 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_Focal {
            get {
                return ResourceManager.GetString("MapUI_Scan_Focal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame Per Cycle 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_FramesPerCycle {
            get {
                return ResourceManager.GetString("MapUI_Scan_FramesPerCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame Time (ms) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_FrameTime {
            get {
                return ResourceManager.GetString("MapUI_Scan_FrameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function Mode 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_FunctionMode {
            get {
                return ResourceManager.GetString("MapUI_Scan_FunctionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gain 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_Gain {
            get {
                return ResourceManager.GetString("MapUI_Scan_Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gantry Acceleration (°/s²) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_GantryAcceleration {
            get {
                return ResourceManager.GetString("MapUI_Scan_GantryAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gantry Acceleration Time (ms) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_GantryAccelerationTime {
            get {
                return ResourceManager.GetString("MapUI_Scan_GantryAccelerationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gantry Direction 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_GantryDirection {
            get {
                return ResourceManager.GetString("MapUI_Scan_GantryDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gantry End (°) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_GantryEnd {
            get {
                return ResourceManager.GetString("MapUI_Scan_GantryEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gantry Speed (°/s) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_GantrySpeed {
            get {
                return ResourceManager.GetString("MapUI_Scan_GantrySpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gantry Start (°) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_GantryStart {
            get {
                return ResourceManager.GetString("MapUI_Scan_GantryStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mAs 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_mAs {
            get {
                return ResourceManager.GetString("MapUI_Scan_mAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object Fov (mm) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_ObjectFov {
            get {
                return ResourceManager.GetString("MapUI_Scan_ObjectFov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pitch 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_Pitch {
            get {
                return ResourceManager.GetString("MapUI_Scan_Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post Delete Length (mm) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_PostDeleteLength {
            get {
                return ResourceManager.GetString("MapUI_Scan_PostDeleteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post Offset 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_PostOffset {
            get {
                return ResourceManager.GetString("MapUI_Scan_PostOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre Offset 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_PreOffset {
            get {
                return ResourceManager.GetString("MapUI_Scan_PreOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R Delay (ms) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_RDelay {
            get {
                return ResourceManager.GetString("MapUI_Scan_RDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recon Volume End (mm) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_ReconVolumeEndPosition {
            get {
                return ResourceManager.GetString("MapUI_Scan_ReconVolumeEndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recon Volume Start (mm) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_ReconVolumeStartPosition {
            get {
                return ResourceManager.GetString("MapUI_Scan_ReconVolumeStartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan Binning 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_ScanBinning {
            get {
                return ResourceManager.GetString("MapUI_Scan_ScanBinning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan Fov (mm) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_ScanFOV {
            get {
                return ResourceManager.GetString("MapUI_Scan_ScanFOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan Length (mm) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_ScanLength {
            get {
                return ResourceManager.GetString("MapUI_Scan_ScanLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan Mode 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_ScanMode {
            get {
                return ResourceManager.GetString("MapUI_Scan_ScanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan Option 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_ScanOption {
            get {
                return ResourceManager.GetString("MapUI_Scan_ScanOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan UID 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_ScanUID {
            get {
                return ResourceManager.GetString("MapUI_Scan_ScanUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Acceleration (mm/s²) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_TableAcceleration {
            get {
                return ResourceManager.GetString("MapUI_Scan_TableAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Acceleration Time (ms) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_TableAccelerationTime {
            get {
                return ResourceManager.GetString("MapUI_Scan_TableAccelerationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Direction 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_TableDirection {
            get {
                return ResourceManager.GetString("MapUI_Scan_TableDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Feed (mm) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_TableFeed {
            get {
                return ResourceManager.GetString("MapUI_Scan_TableFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Height (mm) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_TableHeight {
            get {
                return ResourceManager.GetString("MapUI_Scan_TableHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Speed (mm/s) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_TableSpeed {
            get {
                return ResourceManager.GetString("MapUI_Scan_TableSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T Delay (ms) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_TDelay {
            get {
                return ResourceManager.GetString("MapUI_Scan_TDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tube Positions 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_TubePositions {
            get {
                return ResourceManager.GetString("MapUI_Scan_TubePositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Voltage (kV) 的本地化字符串。
        /// </summary>
        public static string MapUI_Scan_Voltage {
            get {
                return ResourceManager.GetString("MapUI_Scan_Voltage", resourceCulture);
            }
        }
    }
}
