//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV.CT.Service.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Config_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Config_Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NV.CT.Service.Common.Resources.Config_Lang", typeof(Config_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Acquisition Board 的本地化字符串。
        /// </summary>
        public static string Config_ACQBox {
            get {
                return ResourceManager.GetString("Config_ACQBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anode Driver Unit 的本地化字符串。
        /// </summary>
        public static string Config_ADU {
            get {
                return ResourceManager.GetString("Config_ADU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multifunction Control Board 的本地化字符串。
        /// </summary>
        public static string Config_AuxBox {
            get {
                return ResourceManager.GetString("Config_AuxBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Breath Navigation 的本地化字符串。
        /// </summary>
        public static string Config_BNV {
            get {
                return ResourceManager.GetString("Config_BNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control Box 的本地化字符串。
        /// </summary>
        public static string Config_COB {
            get {
                return ResourceManager.GetString("Config_COB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coll Board 的本地化字符串。
        /// </summary>
        public static string Config_Coll {
            get {
                return ResourceManager.GetString("Config_Coll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Central Control Board 的本地化字符串。
        /// </summary>
        public static string Config_CTBox {
            get {
                return ResourceManager.GetString("Config_CTBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detector Module 的本地化字符串。
        /// </summary>
        public static string Config_DetectorModule {
            get {
                return ResourceManager.GetString("Config_DetectorModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gantry Servo 的本地化字符串。
        /// </summary>
        public static string Config_GantryServo {
            get {
                return ResourceManager.GetString("Config_GantryServo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gantry Control Panel 的本地化字符串。
        /// </summary>
        public static string Config_GCP {
            get {
                return ResourceManager.GetString("Config_GCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence Control Board 的本地化字符串。
        /// </summary>
        public static string Config_IFBox {
            get {
                return ResourceManager.GetString("Config_IFBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Motion Control Board 的本地化字符串。
        /// </summary>
        public static string Config_MtCtrlBox {
            get {
                return ResourceManager.GetString("Config_MtCtrlBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDU Board 的本地化字符串。
        /// </summary>
        public static string Config_PduBox {
            get {
                return ResourceManager.GetString("Config_PduBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Board 的本地化字符串。
        /// </summary>
        public static string Config_ProcessBox {
            get {
                return ResourceManager.GetString("Config_ProcessBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contrast Scale  的本地化字符串。
        /// </summary>
        public static string Config_QT_ContrastScale {
            get {
                return ResourceManager.GetString("Config_QT_ContrastScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CT of Water 的本地化字符串。
        /// </summary>
        public static string Config_QT_CTWater {
            get {
                return ResourceManager.GetString("Config_QT_CTWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Homogeneity 的本地化字符串。
        /// </summary>
        public static string Config_QT_Homogeneity {
            get {
                return ResourceManager.GetString("Config_QT_Homogeneity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High-contrast Spatial Resolution-XY 的本地化字符串。
        /// </summary>
        public static string Config_QT_MTF_XY {
            get {
                return ResourceManager.GetString("Config_QT_MTF_XY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High-contrast Spatial Resolution-Z 的本地化字符串。
        /// </summary>
        public static string Config_QT_MTF_Z {
            get {
                return ResourceManager.GetString("Config_QT_MTF_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Noise of Water 的本地化字符串。
        /// </summary>
        public static string Config_QT_NoiseWater {
            get {
                return ResourceManager.GetString("Config_QT_NoiseWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Place Phantom 的本地化字符串。
        /// </summary>
        public static string Config_QT_Phantom {
            get {
                return ResourceManager.GetString("Config_QT_Phantom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slice Thickness-Axial Scan 的本地化字符串。
        /// </summary>
        public static string Config_QT_SliceThickness_Axial {
            get {
                return ResourceManager.GetString("Config_QT_SliceThickness_Axial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slice Thickness-Helical Scan 的本地化字符串。
        /// </summary>
        public static string Config_QT_SliceThickness_Helical {
            get {
                return ResourceManager.GetString("Config_QT_SliceThickness_Helical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patient Table Control Board 的本地化字符串。
        /// </summary>
        public static string Config_TableBox {
            get {
                return ResourceManager.GetString("Config_TableBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Servo X 的本地化字符串。
        /// </summary>
        public static string Config_TableServoX {
            get {
                return ResourceManager.GetString("Config_TableServoX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Servo Y 的本地化字符串。
        /// </summary>
        public static string Config_TableServoY {
            get {
                return ResourceManager.GetString("Config_TableServoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Servo Z 的本地化字符串。
        /// </summary>
        public static string Config_TableServoZ {
            get {
                return ResourceManager.GetString("Config_TableServoZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temperature Control Board 的本地化字符串。
        /// </summary>
        public static string Config_TempBox {
            get {
                return ResourceManager.GetString("Config_TempBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transmission Board 的本地化字符串。
        /// </summary>
        public static string Config_TransmitBox {
            get {
                return ResourceManager.GetString("Config_TransmitBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High-voltage Interface Board 的本地化字符串。
        /// </summary>
        public static string Config_TubeintfBox {
            get {
                return ResourceManager.GetString("Config_TubeintfBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X Ray Board 的本地化字符串。
        /// </summary>
        public static string Config_XRay {
            get {
                return ResourceManager.GetString("Config_XRay", resourceCulture);
            }
        }
    }
}
