//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV.CT.Service.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HardwareTest_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HardwareTest_Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NV.CT.Service.Common.Resources.HardwareTest_Lang", typeof(HardwareTest_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Exposure Time (ms) 的本地化字符串。
        /// </summary>
        public static string Hardware_ExposureTime {
            get {
                return ResourceManager.GetString("Hardware_ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame Time (ms) 的本地化字符串。
        /// </summary>
        public static string Hardware_FrameTime {
            get {
                return ResourceManager.GetString("Hardware_FrameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gantry Angle (°) 的本地化字符串。
        /// </summary>
        public static string Hardware_GantryAngle {
            get {
                return ResourceManager.GetString("Hardware_GantryAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters 的本地化字符串。
        /// </summary>
        public static string Hardware_Parameters {
            get {
                return ResourceManager.GetString("Hardware_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save configuration file 的本地化字符串。
        /// </summary>
        public static string Hardware_SaveConfigFailed {
            get {
                return ResourceManager.GetString("Hardware_SaveConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Successful 的本地化字符串。
        /// </summary>
        public static string Hardware_SetSuccess {
            get {
                return ResourceManager.GetString("Hardware_SetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Frames 的本地化字符串。
        /// </summary>
        public static string Hardware_TotalFrames {
            get {
                return ResourceManager.GetString("Hardware_TotalFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus 的本地化字符串。
        /// </summary>
        public static string Hardware_XRayFocus {
            get {
                return ResourceManager.GetString("Hardware_XRayFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are identical kV/mA pairs 的本地化字符串。
        /// </summary>
        public static string Hardware_XRaySource_KVMACoefficients_Add_AlreadyExist {
            get {
                return ResourceManager.GetString("Hardware_XRaySource_KVMACoefficients_Add_AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coefficients 的本地化字符串。
        /// </summary>
        public static string Hardware_XRaySource_KVMACoefficients_Coefficients {
            get {
                return ResourceManager.GetString("Hardware_XRaySource_KVMACoefficients_Coefficients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete {0}kV/{1}mA pair? 的本地化字符串。
        /// </summary>
        public static string Hardware_XRaySource_KVMACoefficients_DeleteConfirm {
            get {
                return ResourceManager.GetString("Hardware_XRaySource_KVMACoefficients_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door is not closed, please close the door! 的本地化字符串。
        /// </summary>
        public static string Hardware_XRaySource_KVMACoefficients_DoorNotClose {
            get {
                return ResourceManager.GetString("Hardware_XRaySource_KVMACoefficients_DoorNotClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exposure Parameters 的本地化字符串。
        /// </summary>
        public static string Hardware_XRaySource_KVMACoefficients_ExposureParam {
            get {
                return ResourceManager.GetString("Hardware_XRaySource_KVMACoefficients_ExposureParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Factor 的本地化字符串。
        /// </summary>
        public static string Hardware_XRaySource_KVMACoefficients_Factor {
            get {
                return ResourceManager.GetString("Hardware_XRaySource_KVMACoefficients_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kV/mA Pairs 的本地化字符串。
        /// </summary>
        public static string Hardware_XRaySource_KVMACoefficients_KVMAPairs {
            get {
                return ResourceManager.GetString("Hardware_XRaySource_KVMACoefficients_KVMAPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12 o‘clock Benchmark 的本地化字符串。
        /// </summary>
        public static string Hardware_XRaySource_KVMACoefficients_SourceAndGantryBase {
            get {
                return ResourceManager.GetString("Hardware_XRaySource_KVMACoefficients_SourceAndGantryBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Exposure 的本地化字符串。
        /// </summary>
        public static string Hardware_XRaySource_KVMACoefficients_StartExposure {
            get {
                return ResourceManager.GetString("Hardware_XRaySource_KVMACoefficients_StartExposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Exposure Failed: {0} 的本地化字符串。
        /// </summary>
        public static string Hardware_XRaySource_KVMACoefficients_StartExposure_Failed {
            get {
                return ResourceManager.GetString("Hardware_XRaySource_KVMACoefficients_StartExposure_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Exposure 的本地化字符串。
        /// </summary>
        public static string Hardware_XRaySource_KVMACoefficients_StopExposure {
            get {
                return ResourceManager.GetString("Hardware_XRaySource_KVMACoefficients_StopExposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Exposure Failed 的本地化字符串。
        /// </summary>
        public static string Hardware_XRaySource_KVMACoefficients_StopExposure_Failed {
            get {
                return ResourceManager.GetString("Hardware_XRaySource_KVMACoefficients_StopExposure_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source ID 的本地化字符串。
        /// </summary>
        public static string Hardware_XRaySource_SourceId {
            get {
                return ResourceManager.GetString("Hardware_XRaySource_SourceId", resourceCulture);
            }
        }
    }
}
