//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV.CT.Service.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Quality_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Quality_Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NV.CT.Service.Common.Resources.Quality_Lang", typeof(Quality_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Fail to obtain wire position: {1} 的本地化字符串。
        /// </summary>
        public static string Quality_Alg_GetMetalFail {
            get {
                return ResourceManager.GetString("Quality_Alg_GetMetalFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Algorithm invoke error: {0} 的本地化字符串。
        /// </summary>
        public static string Quality_Alg_InvokeError {
            get {
                return ResourceManager.GetString("Quality_Alg_InvokeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse Report 的本地化字符串。
        /// </summary>
        public static string Quality_BrowseReport {
            get {
                return ResourceManager.GetString("Quality_BrowseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Offline Recon 的本地化字符串。
        /// </summary>
        public static string Quality_Buton_StopOfflineRecon {
            get {
                return ResourceManager.GetString("Quality_Buton_StopOfflineRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Scan Recon 的本地化字符串。
        /// </summary>
        public static string Quality_Button_StopScanRecon {
            get {
                return ResourceManager.GetString("Quality_Button_StopScanRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan or offline-recon in progress, please don&apos;t leave! 的本地化字符串。
        /// </summary>
        public static string Quality_Close_InScanOrRecon {
            get {
                return ResourceManager.GetString("Quality_Close_InScanOrRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to remove the raw data? 的本地化字符串。
        /// </summary>
        public static string Quality_DeleteRawData {
            get {
                return ResourceManager.GetString("Quality_DeleteRawData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collection queue has been canceled, but the current collection has been completed and the raw data cannot be removed. 的本地化字符串。
        /// </summary>
        public static string Quality_DeleteRawData_ScanComplete {
            get {
                return ResourceManager.GetString("Quality_DeleteRawData_ScanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Angle 的本地化字符串。
        /// </summary>
        public static string Quality_Image_Angle {
            get {
                return ResourceManager.GetString("Quality_Image_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Correction View 的本地化字符串。
        /// </summary>
        public static string Quality_Image_CorrView {
            get {
                return ResourceManager.GetString("Quality_Image_CorrView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut View 的本地化字符串。
        /// </summary>
        public static string Quality_Image_CutView {
            get {
                return ResourceManager.GetString("Quality_Image_CutView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Quality_Image_Delete {
            get {
                return ResourceManager.GetString("Quality_Image_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ellipse 的本地化字符串。
        /// </summary>
        public static string Quality_Image_Ellipse {
            get {
                return ResourceManager.GetString("Quality_Image_Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit 的本地化字符串。
        /// </summary>
        public static string Quality_Image_Fit {
            get {
                return ResourceManager.GetString("Quality_Image_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Image control can not find AnnotationCard 的本地化字符串。
        /// </summary>
        public static string Quality_Image_IC_AnnoCardNotFind {
            get {
                return ResourceManager.GetString("Quality_Image_IC_AnnoCardNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter type error: {0} 的本地化字符串。
        /// </summary>
        public static string Quality_Image_ModelTypeError {
            get {
                return ResourceManager.GetString("Quality_Image_ModelTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string Quality_Image_None {
            get {
                return ResourceManager.GetString("Quality_Image_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1:1 的本地化字符串。
        /// </summary>
        public static string Quality_Image_OneToOne {
            get {
                return ResourceManager.GetString("Quality_Image_OneToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pan 的本地化字符串。
        /// </summary>
        public static string Quality_Image_Pan {
            get {
                return ResourceManager.GetString("Quality_Image_Pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raw View 的本地化字符串。
        /// </summary>
        public static string Quality_Image_RawView {
            get {
                return ResourceManager.GetString("Quality_Image_RawView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reconstruction View 的本地化字符串。
        /// </summary>
        public static string Quality_Image_ReconView {
            get {
                return ResourceManager.GetString("Quality_Image_ReconView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rectangular 的本地化字符串。
        /// </summary>
        public static string Quality_Image_Rect {
            get {
                return ResourceManager.GetString("Quality_Image_Rect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sinogram View 的本地化字符串。
        /// </summary>
        public static string Quality_Image_SinogramView {
            get {
                return ResourceManager.GetString("Quality_Image_SinogramView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom 的本地化字符串。
        /// </summary>
        public static string Quality_Image_Zoom {
            get {
                return ResourceManager.GetString("Quality_Image_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Items 的本地化字符串。
        /// </summary>
        public static string Quality_Items {
            get {
                return ResourceManager.GetString("Quality_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MTF Curve 的本地化字符串。
        /// </summary>
        public static string Quality_MTF_Curve {
            get {
                return ResourceManager.GetString("Quality_MTF_Curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number 的本地化字符串。
        /// </summary>
        public static string Quality_Number {
            get {
                return ResourceManager.GetString("Quality_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} offline reconstruction begin 的本地化字符串。
        /// </summary>
        public static string Quality_OfflineRecon_Begin {
            get {
                return ResourceManager.GetString("Quality_OfflineRecon_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} offline reconstruction cancelled 的本地化字符串。
        /// </summary>
        public static string Quality_OfflineRecon_Cancel {
            get {
                return ResourceManager.GetString("Quality_OfflineRecon_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} offline reconstruction completed 的本地化字符串。
        /// </summary>
        public static string Quality_OfflineRecon_Complete {
            get {
                return ResourceManager.GetString("Quality_OfflineRecon_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} offline reconstruction create task failed: {1} 的本地化字符串。
        /// </summary>
        public static string Quality_OfflineRecon_CreateFail {
            get {
                return ResourceManager.GetString("Quality_OfflineRecon_CreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} offline reconstruction failed: {1} 的本地化字符串。
        /// </summary>
        public static string Quality_OfflineRecon_Error {
            get {
                return ResourceManager.GetString("Quality_OfflineRecon_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} offline reconstruction data does not exist: {1} 的本地化字符串。
        /// </summary>
        public static string Quality_OfflineRecon_FolderNotExist {
            get {
                return ResourceManager.GetString("Quality_OfflineRecon_FolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} offline reconstruction start task failed: {1} 的本地化字符串。
        /// </summary>
        public static string Quality_OfflineRecon_StartFail {
            get {
                return ResourceManager.GetString("Quality_OfflineRecon_StartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} offline reconstruction stop task failed: {1} 的本地化字符串。
        /// </summary>
        public static string Quality_OfflineRecon_StopFail {
            get {
                return ResourceManager.GetString("Quality_OfflineRecon_StopFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string Quality_Operation {
            get {
                return ResourceManager.GetString("Quality_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Address : 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Address {
            get {
                return ResourceManager.GetString("Quality_Report_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body Part 的本地化字符串。
        /// </summary>
        public static string Quality_Report_BodyPart {
            get {
                return ResourceManager.GetString("Quality_Report_BodyPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Export Path 的本地化字符串。
        /// </summary>
        public static string Quality_Report_ChooseExportPath {
            get {
                return ResourceManager.GetString("Quality_Report_ChooseExportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executed By : 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Executed {
            get {
                return ResourceManager.GetString("Quality_Report_Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First 的本地化字符串。
        /// </summary>
        public static string Quality_Report_First {
            get {
                return ResourceManager.GetString("Quality_Report_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date of Report Generation : 的本地化字符串。
        /// </summary>
        public static string Quality_Report_GenerationData {
            get {
                return ResourceManager.GetString("Quality_Report_GenerationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report Header Information 的本地化字符串。
        /// </summary>
        public static string Quality_Report_HeadInfo {
            get {
                return ResourceManager.GetString("Quality_Report_HeadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Items {
            get {
                return ResourceManager.GetString("Quality_Report_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Last {
            get {
                return ResourceManager.GetString("Quality_Report_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Session Data : 的本地化字符串。
        /// </summary>
        public static string Quality_Report_LastData {
            get {
                return ResourceManager.GetString("Quality_Report_LastData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Max {
            get {
                return ResourceManager.GetString("Quality_Report_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Middle 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Middle {
            get {
                return ResourceManager.GetString("Quality_Report_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Min {
            get {
                return ResourceManager.GetString("Quality_Report_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Name : 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Name {
            get {
                return ResourceManager.GetString("Quality_Report_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Parameters {
            get {
                return ResourceManager.GetString("Quality_Report_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phantom S/N : 的本地化字符串。
        /// </summary>
        public static string Quality_Report_PhantomSN {
            get {
                return ResourceManager.GetString("Quality_Report_PhantomSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reason : 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Reason {
            get {
                return ResourceManager.GetString("Quality_Report_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Reference {
            get {
                return ResourceManager.GetString("Quality_Report_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Region of Interest 的本地化字符串。
        /// </summary>
        public static string Quality_Report_ROI {
            get {
                return ResourceManager.GetString("Quality_Report_ROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan # 的本地化字符串。
        /// </summary>
        public static string Quality_Report_ScanNo {
            get {
                return ResourceManager.GetString("Quality_Report_ScanNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signature : 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Signature {
            get {
                return ResourceManager.GetString("Quality_Report_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System S/N : 的本地化字符串。
        /// </summary>
        public static string Quality_Report_SystemSN {
            get {
                return ResourceManager.GetString("Quality_Report_SystemSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performance Report 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Title {
            get {
                return ResourceManager.GetString("Quality_Report_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlimited 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Unlimited {
            get {
                return ResourceManager.GetString("Quality_Report_Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software Version : 的本地化字符串。
        /// </summary>
        public static string Quality_Report_Version {
            get {
                return ResourceManager.GetString("Quality_Report_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation Log 的本地化字符串。
        /// </summary>
        public static string Quality_RunLog {
            get {
                return ResourceManager.GetString("Quality_RunLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The verification before acquisition start fails: {0} 的本地化字符串。
        /// </summary>
        public static string Quality_Scan_BeforeFail {
            get {
                return ResourceManager.GetString("Quality_Scan_BeforeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} acquisition and reconstruction begin 的本地化字符串。
        /// </summary>
        public static string Quality_Scan_Begin {
            get {
                return ResourceManager.GetString("Quality_Scan_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acquisition and reconstruction cancelled 的本地化字符串。
        /// </summary>
        public static string Quality_Scan_Cancel {
            get {
                return ResourceManager.GetString("Quality_Scan_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acquisition and reconstruction completed 的本地化字符串。
        /// </summary>
        public static string Quality_Scan_Complete {
            get {
                return ResourceManager.GetString("Quality_Scan_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The creation of scanning parameters failed 的本地化字符串。
        /// </summary>
        public static string Quality_Scan_CreateParamFail {
            get {
                return ResourceManager.GetString("Quality_Scan_CreateParamFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acquisition and reconstruction failed: {0} 的本地化字符串。
        /// </summary>
        public static string Quality_Scan_Error {
            get {
                return ResourceManager.GetString("Quality_Scan_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The start of acquisition failed: the previous acquisition and reconstruction is still running 的本地化字符串。
        /// </summary>
        public static string Quality_Scan_Fail_PreviousRunning {
            get {
                return ResourceManager.GetString("Quality_Scan_Fail_PreviousRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The start of acquisition failed: {0} 的本地化字符串。
        /// </summary>
        public static string Quality_Scan_StartFail {
            get {
                return ResourceManager.GetString("Quality_Scan_StartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The stop of acquisition failed: {0} 的本地化字符串。
        /// </summary>
        public static string Quality_Scan_StopFail {
            get {
                return ResourceManager.GetString("Quality_Scan_StopFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        public static string Quality_UC_Center {
            get {
                return ResourceManager.GetString("Quality_UC_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        public static string Quality_UC_Left {
            get {
                return ResourceManager.GetString("Quality_UC_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The phantom is not in the center of the aperture 的本地化字符串。
        /// </summary>
        public static string Quality_UC_PhantomNoCenter {
            get {
                return ResourceManager.GetString("Quality_UC_PhantomNoCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phantom Tilt 的本地化字符串。
        /// </summary>
        public static string Quality_UC_PhantomTilt {
            get {
                return ResourceManager.GetString("Quality_UC_PhantomTilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Position (Z) 的本地化字符串。
        /// </summary>
        public static string Quality_UC_Position {
            get {
                return ResourceManager.GetString("Quality_UC_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        public static string Quality_UC_Right {
            get {
                return ResourceManager.GetString("Quality_UC_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choose which image data to use? 的本地化字符串。
        /// </summary>
        public static string Quality_UC_SelectImage {
            get {
                return ResourceManager.GetString("Quality_UC_SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validate Result: 的本地化字符串。
        /// </summary>
        public static string Quality_UC_ValidateResult {
            get {
                return ResourceManager.GetString("Quality_UC_ValidateResult", resourceCulture);
            }
        }
    }
}
