//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV.CT.Service.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Upgrade_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Upgrade_Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NV.CT.Service.Common.Resources.Upgrade_Lang", typeof(Upgrade_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} can select, {1} select, {2} success, {3} failed 的本地化字符串。
        /// </summary>
        public static string Upgrade_Info_CountInfo {
            get {
                return ResourceManager.GetString("Upgrade_Info_CountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Version 的本地化字符串。
        /// </summary>
        public static string Upgrade_Info_CurrentVersion {
            get {
                return ResourceManager.GetString("Upgrade_Info_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No upgrade when the version is the same 的本地化字符串。
        /// </summary>
        public static string Upgrade_Info_NotWhenSameVer {
            get {
                return ResourceManager.GetString("Upgrade_Info_NotWhenSameVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade Patch Path 的本地化字符串。
        /// </summary>
        public static string Upgrade_Info_Path {
            get {
                return ResourceManager.GetString("Upgrade_Info_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress 的本地化字符串。
        /// </summary>
        public static string Upgrade_Info_Progress {
            get {
                return ResourceManager.GetString("Upgrade_Info_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Superior Name 的本地化字符串。
        /// </summary>
        public static string Upgrade_Info_SuperiorName {
            get {
                return ResourceManager.GetString("Upgrade_Info_SuperiorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgradable Status 的本地化字符串。
        /// </summary>
        public static string Upgrade_Info_UpgradableStatus {
            get {
                return ResourceManager.GetString("Upgrade_Info_UpgradableStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade 的本地化字符串。
        /// </summary>
        public static string Upgrade_Info_Upgrade {
            get {
                return ResourceManager.GetString("Upgrade_Info_Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade Status 的本地化字符串。
        /// </summary>
        public static string Upgrade_Info_UpgradeStatus {
            get {
                return ResourceManager.GetString("Upgrade_Info_UpgradeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade Version 的本地化字符串。
        /// </summary>
        public static string Upgrade_Info_UpgradeVersion {
            get {
                return ResourceManager.GetString("Upgrade_Info_UpgradeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current version does not match the upgrade version 的本地化字符串。
        /// </summary>
        public static string Upgrade_Info_VersionNotMatch {
            get {
                return ResourceManager.GetString("Upgrade_Info_VersionNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are unsuccessful firmware after the upgrade, please confirm before leaving! 的本地化字符串。
        /// </summary>
        public static string Upgrade_Leave_Confirm {
            get {
                return ResourceManager.GetString("Upgrade_Leave_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrading in progress, please do not leave! 的本地化字符串。
        /// </summary>
        public static string Upgrade_Leave_InUpgrading {
            get {
                return ResourceManager.GetString("Upgrade_Leave_InUpgrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The upgrade is completed 的本地化字符串。
        /// </summary>
        public static string Upgrade_StepInfo_Completed {
            get {
                return ResourceManager.GetString("Upgrade_StepInfo_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get version after self check 的本地化字符串。
        /// </summary>
        public static string Upgrade_StepInfo_GetVersionAfterSelfCheck {
            get {
                return ResourceManager.GetString("Upgrade_StepInfo_GetVersionAfterSelfCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrading in progress, unable to upgrade again 的本地化字符串。
        /// </summary>
        public static string Upgrade_StepInfo_InUpgrading {
            get {
                return ResourceManager.GetString("Upgrade_StepInfo_InUpgrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no upgradable firmware 的本地化字符串。
        /// </summary>
        public static string Upgrade_StepInfo_NoCanUpgrade {
            get {
                return ResourceManager.GetString("Upgrade_StepInfo_NoCanUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware upgrade prepare command error 的本地化字符串。
        /// </summary>
        public static string Upgrade_StepInfo_PrepareCommandError {
            get {
                return ResourceManager.GetString("Upgrade_StepInfo_PrepareCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send power restart command 的本地化字符串。
        /// </summary>
        public static string Upgrade_StepInfo_SendPowerRestartCommand {
            get {
                return ResourceManager.GetString("Upgrade_StepInfo_SendPowerRestartCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send hardware upgrade prepare command 的本地化字符串。
        /// </summary>
        public static string Upgrade_StepInfo_SendUpgradePrepareCommand {
            get {
                return ResourceManager.GetString("Upgrade_StepInfo_SendUpgradePrepareCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set ctbox to upgrading status 的本地化字符串。
        /// </summary>
        public static string Upgrade_StepInfo_SetUpgradingStatus {
            get {
                return ResourceManager.GetString("Upgrade_StepInfo_SetUpgradingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrading... 的本地化字符串。
        /// </summary>
        public static string Upgrade_StepInfo_Upgrading {
            get {
                return ResourceManager.GetString("Upgrade_StepInfo_Upgrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait power restart and hardware self check result 的本地化字符串。
        /// </summary>
        public static string Upgrade_StepInfo_WaitPowerRestartAndSelfCheckResult {
            get {
                return ResourceManager.GetString("Upgrade_StepInfo_WaitPowerRestartAndSelfCheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware is preparing for upgrade, wait... 的本地化字符串。
        /// </summary>
        public static string Upgrade_StepInfo_WaitPrepareResult {
            get {
                return ResourceManager.GetString("Upgrade_StepInfo_WaitPrepareResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The upgrade is completed. 的本地化字符串。
        /// </summary>
        public static string Upgrade_Upgrade_Completed {
            get {
                return ResourceManager.GetString("Upgrade_Upgrade_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1}
        ///Power restart automatically, please wait for restart to complete. 的本地化字符串。
        /// </summary>
        public static string Upgrade_Upgrade_DialogMsg_FailedBeforeUpgrade {
            get {
                return ResourceManager.GetString("Upgrade_Upgrade_DialogMsg_FailedBeforeUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1}
        ///Power restart automatically failed: {2}
        ///Please restart the power manually and wait for restart to complete. 的本地化字符串。
        /// </summary>
        public static string Upgrade_Upgrade_DialogMsg_FailedBeforeUpgradeAndREstartPowerError {
            get {
                return ResourceManager.GetString("Upgrade_Upgrade_DialogMsg_FailedBeforeUpgradeAndREstartPowerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrading in progress, unable to upgrade again 的本地化字符串。
        /// </summary>
        public static string Upgrade_Upgrade_DialogMsg_InUpgrading {
            get {
                return ResourceManager.GetString("Upgrade_Upgrade_DialogMsg_InUpgrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no upgradable firmware. 的本地化字符串。
        /// </summary>
        public static string Upgrade_Upgrade_DialogMsg_NoCanUpgrade {
            get {
                return ResourceManager.GetString("Upgrade_Upgrade_DialogMsg_NoCanUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware upgrade prepare command error 的本地化字符串。
        /// </summary>
        public static string Upgrade_Upgrade_DialogMsg_Part_PrepareCommandError {
            get {
                return ResourceManager.GetString("Upgrade_Upgrade_DialogMsg_Part_PrepareCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware upgrade prepare failed 的本地化字符串。
        /// </summary>
        public static string Upgrade_Upgrade_DialogMsg_Part_PrepareResultError {
            get {
                return ResourceManager.GetString("Upgrade_Upgrade_DialogMsg_Part_PrepareResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set ctbox to upgrading status failed 的本地化字符串。
        /// </summary>
        public static string Upgrade_Upgrade_DialogMsg_Part_SetUpgradingStatusError {
            get {
                return ResourceManager.GetString("Upgrade_Upgrade_DialogMsg_Part_SetUpgradingStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The upgrade is completed, but power restart automatically failed: {0}
        ///Please restart the power manually and wait for restart to complete. 的本地化字符串。
        /// </summary>
        public static string Upgrade_Upgrade_DialogMsg_RestartPowerCommandError {
            get {
                return ResourceManager.GetString("Upgrade_Upgrade_DialogMsg_RestartPowerCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The upgrade is completed, please restart the power manually and wait for restart to complete. 的本地化字符串。
        /// </summary>
        public static string Upgrade_Upgrade_DialogMsg_RestartPowreManually {
            get {
                return ResourceManager.GetString("Upgrade_Upgrade_DialogMsg_RestartPowreManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get version after restart power. 的本地化字符串。
        /// </summary>
        public static string Upgrade_Upgrade_Fail_GetVerError {
            get {
                return ResourceManager.GetString("Upgrade_Upgrade_Fail_GetVerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The version after restart power does not match the upgrade verision. 的本地化字符串。
        /// </summary>
        public static string Upgrade_Upgrade_Fail_VerNotMatch {
            get {
                return ResourceManager.GetString("Upgrade_Upgrade_Fail_VerNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following firmwares upgrade failed: 
        ///{0} 的本地化字符串。
        /// </summary>
        public static string Upgrade_Upgrade_FailedItems {
            get {
                return ResourceManager.GetString("Upgrade_Upgrade_FailedItems", resourceCulture);
            }
        }
    }
}
