//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV.CT.Service.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Warmup_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Warmup_Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NV.CT.Service.Common.Resources.Warmup_Lang", typeof(Warmup_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Elapsed Time: 的本地化字符串。
        /// </summary>
        public static string Warmup_ElapsedTime {
            get {
                return ResourceManager.GetString("Warmup_ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. There is nobody in the scanning room 的本地化字符串。
        /// </summary>
        public static string Warmup_Hint1 {
            get {
                return ResourceManager.GetString("Warmup_Hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2. The scanning room is closed 的本地化字符串。
        /// </summary>
        public static string Warmup_Hint2 {
            get {
                return ResourceManager.GetString("Warmup_Hint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please confirm these following precautions before confirming the operation: 的本地化字符串。
        /// </summary>
        public static string Warmup_HintTitle {
            get {
                return ResourceManager.GetString("Warmup_HintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oil Temperature 的本地化字符串。
        /// </summary>
        public static string Warmup_OilTemperature {
            get {
                return ResourceManager.GetString("Warmup_OilTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warmup Count 的本地化字符串。
        /// </summary>
        public static string Warmup_PreheatCount {
            get {
                return ResourceManager.GetString("Warmup_PreheatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warmup Goal(%) 的本地化字符串。
        /// </summary>
        public static string Warmup_PreheatGoal {
            get {
                return ResourceManager.GetString("Warmup_PreheatGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rest Interval 的本地化字符串。
        /// </summary>
        public static string Warmup_RestInterval {
            get {
                return ResourceManager.GetString("Warmup_RestInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan Task 的本地化字符串。
        /// </summary>
        public static string Warmup_ScanTask {
            get {
                return ResourceManager.GetString("Warmup_ScanTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan Times 的本地化字符串。
        /// </summary>
        public static string Warmup_ScanTimes {
            get {
                return ResourceManager.GetString("Warmup_ScanTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop warm up 的本地化字符串。
        /// </summary>
        public static string Warmup_StopWarmup {
            get {
                return ResourceManager.GetString("Warmup_StopWarmup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task Number 的本地化字符串。
        /// </summary>
        public static string Warmup_TaskNumber {
            get {
                return ResourceManager.GetString("Warmup_TaskNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thermal Capacity(%) 的本地化字符串。
        /// </summary>
        public static string Warmup_ThermalCapacity {
            get {
                return ResourceManager.GetString("Warmup_ThermalCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tube 的本地化字符串。
        /// </summary>
        public static string Warmup_Tube {
            get {
                return ResourceManager.GetString("Warmup_Tube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tube Number 的本地化字符串。
        /// </summary>
        public static string Warmup_TubeNumber {
            get {
                return ResourceManager.GetString("Warmup_TubeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tube Status 的本地化字符串。
        /// </summary>
        public static string Warmup_TubeStatus {
            get {
                return ResourceManager.GetString("Warmup_TubeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warm up 的本地化字符串。
        /// </summary>
        public static string Warmup_Warmup {
            get {
                return ResourceManager.GetString("Warmup_Warmup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warm up fail 的本地化字符串。
        /// </summary>
        public static string Warmup_WarmupFail {
            get {
                return ResourceManager.GetString("Warmup_WarmupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warm up success 的本地化字符串。
        /// </summary>
        public static string Warmup_WarmupSuccess {
            get {
                return ResourceManager.GetString("Warmup_WarmupSuccess", resourceCulture);
            }
        }
    }
}
